apiVersion: provisioning.cattle.io/v1
kind: Cluster
metadata:
  annotations:
    objectset.rio.cattle.io/applied: >-
      H4sIAAAAAAAA/4yQzWr7MBDEX+XPnuX8kyhfFvRQSumh177AWtomaqSVkdbuIfjdi+1AQ6EfR2lnht/MBSIJOhQEcwFkToLiE5fxmZo3slJIFtmnhUWRQAuf/nsHBtqcel98Ys/HyoauCOXKZkIhUN9a0ztTro79GQxEZDxSJJYbQa/Vv2fP7u5hjvw1izESGAjJYviTuLRoRwcMCiZen/jFRyqCsQXDXQgKAjYUfhzhhOUEBrbL3X6rdU21xc3BrZr9utZrapb64PZbV7u122x2qwOoeTFH+TMEDJx1GUG+tLjlfA1EUs2XQUFpyY5c08d1pPtOTo/s2uRZwFyGUSYo3bVAodyTeyKmPLUFsxyGjwAAAP//rxALbvoBAAA
    objectset.rio.cattle.io/id: provisioning-cluster-create
    objectset.rio.cattle.io/owner-gvk: management.cattle.io/v3, Kind=Cluster
    objectset.rio.cattle.io/owner-name: local
    objectset.rio.cattle.io/owner-namespace: ''
  creationTimestamp: '2023-11-21T23:12:34Z'
  finalizers:
    - wrangler.cattle.io/cloud-config-secret-remover
    - wrangler.cattle.io/provisioning-cluster-remove
    - wrangler.cattle.io/rke-cluster-remove
  generation: 1
  labels:
    objectset.rio.cattle.io/hash: 50675339e9ca48d1b72932eb038d75d9d2d44618
    provider.cattle.io: k3s
  managedFields:
    - apiVersion: provisioning.cattle.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:finalizers:
            .: {}
            v:"wrangler.cattle.io/cloud-config-secret-remover": {}
      manager: rancher-v2.7.9-secret-migrator
      operation: Update
      time: '2023-11-21T23:12:34Z'
    - apiVersion: provisioning.cattle.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:objectset.rio.cattle.io/applied: {}
            f:objectset.rio.cattle.io/id: {}
            f:objectset.rio.cattle.io/owner-gvk: {}
            f:objectset.rio.cattle.io/owner-name: {}
            f:objectset.rio.cattle.io/owner-namespace: {}
          f:finalizers:
            v:"wrangler.cattle.io/provisioning-cluster-remove": {}
            v:"wrangler.cattle.io/rke-cluster-remove": {}
          f:labels:
            .: {}
            f:objectset.rio.cattle.io/hash: {}
            f:provider.cattle.io: {}
        f:spec:
          .: {}
          f:localClusterAuthEndpoint: {}
      manager: rancher
      operation: Update
      time: '2023-11-21T23:12:42Z'
    - apiVersion: provisioning.cattle.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:status:
          .: {}
          f:clientSecretName: {}
          f:clusterName: {}
          f:conditions: {}
          f:observedGeneration: {}
          f:ready: {}
      manager: rancher
      operation: Update
      subresource: status
      time: '2023-11-21T23:12:53Z'
  name: local
  namespace: fleet-local
  resourceVersion: '2209'
  uid: 584b48b2-b77d-4c8d-86fc-3b4e5c1b8933
spec:
  localClusterAuthEndpoint: {}
status:
  clientSecretName: local-kubeconfig
  clusterName: local
  conditions:
    - status: 'True'
      type: Ready
    - lastUpdateTime: '2023-11-21T23:12:30Z'
      status: 'True'
      type: BackingNamespaceCreated
    - lastUpdateTime: '2023-11-21T23:12:34Z'
      status: 'True'
      type: DefaultProjectCreated
    - lastUpdateTime: '2023-11-21T23:12:34Z'
      status: 'True'
      type: SystemProjectCreated
    - lastUpdateTime: '2023-11-21T23:12:34Z'
      status: 'False'
      type: Reconciling
    - lastUpdateTime: '2023-11-21T23:12:34Z'
      status: 'False'
      type: Stalled
    - lastUpdateTime: '2023-11-21T23:12:53Z'
      status: 'True'
      type: Created
    - lastUpdateTime: '2023-11-21T23:12:35Z'
      status: 'True'
      type: RKECluster
    - lastUpdateTime: '2023-11-21T23:12:34Z'
      status: 'True'
      type: CreatorMadeOwner
    - lastUpdateTime: '2023-11-21T23:12:37Z'
      status: 'True'
      type: Pending
    - lastUpdateTime: '2023-11-21T23:12:53Z'
      status: 'True'
      type: Waiting
    - lastUpdateTime: '2023-11-21T23:12:37Z'
      status: 'True'
      type: NoDiskPressure
    - lastUpdateTime: '2023-11-21T23:12:37Z'
      status: 'True'
      type: NoMemoryPressure
    - lastUpdateTime: '2023-11-21T23:12:38Z'
      status: 'True'
      type: SecretsMigrated
    - lastUpdateTime: '2023-11-21T23:12:38Z'
      status: 'True'
      type: ServiceAccountSecretsMigrated
    - lastUpdateTime: '2023-11-21T23:12:38Z'
      status: 'True'
      type: RKESecretsMigrated
    - lastUpdateTime: '2023-11-21T23:12:38Z'
      status: 'True'
      type: ACISecretsMigrated
    - lastUpdateTime: '2023-11-21T23:12:41Z'
      status: 'True'
      type: SystemAccountCreated
    - lastUpdateTime: '2023-11-21T23:12:42Z'
      status: 'True'
      type: GlobalAdminsSynced
    - lastUpdateTime: '2023-11-21T23:12:45Z'
      status: 'True'
      type: Connected
  observedGeneration: 1
  ready: true
