apiVersion: v1
kind: Config
clusters:
- name: "local"
  cluster:
    server: "https://localhost/k8s/clusters/local"
    certificate-authority-data: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJ2VENDQ\
      VdPZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQkdNUnd3R2dZRFZRUUtFeE5rZVc1aGJXbGoKY\
      kdsemRHVnVaWEl0YjNKbk1TWXdKQVlEVlFRRERCMWtlVzVoYldsamJHbHpkR1Z1WlhJdFkyRkFNV\
      GN3TURZdwpPRE0xTWpBZUZ3MHlNekV4TWpFeU16RXlNekphRncwek16RXhNVGd5TXpFeU16SmFNR\
      Vl4SERBYUJnTlZCQW9UCkUyUjVibUZ0YVdOc2FYTjBaVzVsY2kxdmNtY3hKakFrQmdOVkJBTU1IV\
      1I1Ym1GdGFXTnNhWE4wWlc1bGNpMWoKWVVBeE56QXdOakE0TXpVeU1Ga3dFd1lIS29aSXpqMENBU\
      VlJS29aSXpqMERBUWNEUWdBRUZFZ0k2blNrazFxKwpDcHRXUzkvWFMrRENCdkd1MTRvdXA1UDNKV\
      jdoQjRVWXBEZEx1U2lIWXFQQ3dXdWhmSmVLREljUUNyOVBhdFR0CmYwblhxcEtjY2FOQ01FQXdEZ\
      1lEVlIwUEFRSC9CQVFEQWdLa01BOEdBMVVkRXdFQi93UUZNQU1CQWY4d0hRWUQKVlIwT0JCWUVGR\
      lVwU0tCK3NzK3FOUXMxZnBDd1ZkMmQ5SXhETUFvR0NDcUdTTTQ5QkFNQ0EwZ0FNRVVDSUF3bgpLZ\
      k9SS3R3Y2VyS21RUS9wZUZjS0FVdUd1bE5Ma3gra1FuZ0NlSVFZQWlFQTcxVDFyQStvZitIRHRhc\
      lFtZWRZCjZrWEJqdVVYTnV1MkY3ZFJGUmplbzM0PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0t"

users:
- name: "local"
  user:
    token: "kubeconfig-user-2wfsq6w6wq:s76vr6f6ffw6r4ssspf4grwz79k5j4ffb28v4lmcq8rx2n8s6vvtkw"


contexts:
- name: "local"
  context:
    user: "local"
    cluster: "local"

current-context: "local"
